#!/usr/bin/env bash

# Reproducible builds? Let's see:

set -eu

GO111MODULE=off go clean -x -modcache -cache -testcache
export GO111MODULE=on

rm -f go.mod go.sum
rm -rf vendor

cat <<EOF > go.mod
module github.com/frobware/route-monitor

go 1.12

replace (
	k8s.io/client-go => k8s.io/client-go kubernetes-1.16.1
	k8s.io/apimachinery => k8s.io/apimachinery kubernetes-1.16.1
)
EOF

make
make test
go mod tidy
